AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: >-
  An Amazon Kinesis Firehose stream processor that converts input records from
  Apache Common Log format to JSON.
Parameters: 
  FunctionNameParameter: 
    Type: String
Resources:
  kinesisfirehoseapachelogtojsonpython:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: !Ref FunctionNameParameter
      Handler: app.lambda_handler
      Runtime: python3.6
      CodeUri: ./src
      Description: >-
        An Amazon Kinesis Firehose stream processor that converts input records
        from Apache Common Log format to JSON.
      MemorySize: 128
      Timeout: 3
      Policies:
        - LambdaInvokePolicy:
            FunctionName: !Ref FunctionNameParameter
